apiVersion: apps/v1
kind: Deployment
metadata:
  name: adv-da-ba23-neo4j
  labels:
    app: adv-db-neo4j
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: adv-db-neo4j
  template:
    metadata:
      labels:
        app: adv-db-neo4j
    spec:
      containers:
      - name: importdbneo4jfinal
        image: samuli09/advdb_cython_sub_final
        command: ["sh", "-c", "./neo4j-init.sh"]
        ports:
        - containerPort: 7474  # Neo4j HTTP port
        - containerPort: 7687  # Neo4j Bolt port
        resources:
          requests:
            memory: 2Gi
          limits:
            memory: 3Gi