apiVersion: v1
kind: Pod
metadata:
  name: importwithcythonandnosubfinalv2
spec:
  containers:
  - name: importwithcythonandnosubfinalv2
    image: samuli09/advdb_last_buildv2
    command: ["sh", "-c", "./neo4j-init.sh"]
    ports:
    - containerPort: 7474  # Neo4j HTTP port
    - containerPort: 7687  # Neo4j Bolt port
    resources:
      requests:
        memory: 2Gi
      limits:
        memory: 3Gi